	<script src="{{URL::to('assets/js/jquery.min.js')}}"></script>
	<script src="{{URL::to('assets/js/iframe-content.js')}}"></script>
  	<script src="{{URL::to('assets/Semantic/components/form.js')}}"></script>
  	<script src="{{URL::to('assets/Semantic/components/popup.js')}}"></script>
 	<script src="{{URL::to('assets/Semantic/components/transition.js')}}"></script>
 	<script src="{{URL::to('assets/Semantic/components/dropdown.js')}}"></script>
 	<script src="{{URL::to('assets/sweetalert/sweetalert.min.js')}}"></script>
 	<script src="{{URL::to('assets/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{URL::to('assets/datatables/dataTables.bootstrap.min.js') }}"></script>